name: Build and Release

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows you to trigger the workflow manually

jobs:
  build:
    permissions: write-all  # Required to create a release
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Adjusted to a valid Node.js version

    - name: Install client dependencies and build
      shell: cmd
      working-directory: client
      run: |
        yarn install
        yarn build

    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Use the same version of Python as your project

    - name: Install dependencies
      shell: cmd
      working-directory: server
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Collect static files
      shell: cmd
      working-directory: server
      run: |
        python manage.py collectstatic --noinput

    - name: Build GardenErp executable with PyInstaller
      shell: cmd
      working-directory: server
      run: |
        pyinstaller GardenErp.spec

    - name: Build updater executable with PyInstaller
      shell: cmd
      working-directory: server
      run: |
        pyinstaller updater.spec

    - name: Set Build Name with Short Git SHA
      shell: pwsh
      run: |
        $shortSha = $env:GITHUB_SHA.Substring(0, 8)
        echo "BUILD_NAME=$shortSha" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Create a zip file with the executables and static files
      shell: pwsh
      run: |
        cd server\dist
        mkdir "GardenErp-$env:BUILD_NAME"
        Move-Item GardenErp.exe "GardenErp-$env:BUILD_NAME\"
        Move-Item updater.exe "GardenErp-$env:BUILD_NAME\"
        Move-Item static "GardenErp-$env:BUILD_NAME\static"
        Compress-Archive -Path "GardenErp-$env:BUILD_NAME" -DestinationPath "GardenErp-$env:BUILD_NAME.zip"

    - name: Archive build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: GardenErp-${{ env.BUILD_NAME }}
        path: server\dist\GardenErp-${{ env.BUILD_NAME }}.zip

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.BUILD_NAME }}  # Unique tag name with short Git SHA
        release_name: Release ${{ env.BUILD_NAME }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: server\dist\GardenErp-${{ env.BUILD_NAME }}.zip
        asset_name: GardenErp-${{ env.BUILD_NAME }}.zip
        asset_content_type: application/zip
